### ISSUE TITLE
error after installed

### ISSUE THREAD

**Issue by ghost** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#1]
This error happend after install:

Error: Exception: RecursiveDirectoryIterator::__construct(/home/myserver/public_html/mysite/site/assets/aiom/) [recursivedirectoryiterator.--construct]: failed to open dir: Permission denied (in /home/myserver/public_html/mysite/site/modules/AllInOneMinify/AllInOneMinify.module line 408)

This error message was shown because you are logged in as a Superuser. Error has been logged.

**Comment by ryancramerdesign** [comment]
I ran into the same error. I tracked it down to the mkdir() call, which specifies a mode. However, the mode needs to be run through octdec() before being sent to mkdir(). Example:

```
mkdir($path, octdec(wire('config')->chmodDir), true); 
```

As an alternative, you can use ProcessWire's wireMkdir(), which handles the chmod stuff on its own.

Another minor point I want to mention is that mkdir() doesn't throw exceptions, and the mkdir() in your ___install() function is wrapped in try/catch. What you need to do instead is check the return value of mkdir().

**Comment by ryancramerdesign** [comment]
The same changed (adding octdec) needs to be added in a couple other spots too, btw. Basically anywhere that it references $config->chmodFile or $config->chmodDir. 

So far I'm really enjoying the module btw. Thanks for making it.

**Comment by flipzoom** [comment]
Thank JoZ3 for reporting the error and thank you to Ryan for the quick solution proposal. I have fixed the problem and also the try / catch routine changed. Now the module should work without problems.
