### ISSUE TITLE
Suggestion:  conditional loading

### ISSUE THREAD

**Issue by ghost** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#10]
As always, thank you very much for your work with this module, I am using it in every project I'm working on. would be interesting to have the option to upload each file conditionally, eg:

<?php echo AIOM::CSS(array('css/file-1.css:[id]', 'css/file-2.less', 'css/file-3.css', 'css/file-4.less')); ?>

where [id] is the ID of the page, without the [id] would load on all pages.

**Comment by flipzoom** [comment]
Excellent suggestion! I'm still thinking about the syntax, but definitely write this function on the To-Do. Thank you.

**Comment by flipzoom** [comment]
Now, in Version 3.1.1, conditional loading is implemented. Documentation under the following link: https://github.com/FlipZoomMedia/ProcessWire-AIOM-All-In-One-Minify#conditional-loading
