### ISSUE TITLE
[BUG] AllInOneMinify::_getFileInfoArray():751

### ISSUE THREAD

**Issue by gusdecool** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#12]
on line 751 You should not replace "../" dir to "". It had different meaning with "./"

``` php
// Fix Error, you should not replace "../" to ""
        //$_path  = str_ireplace(array('../', './', '%2e%2e%2f', '..%2F'), '', (wire('config')->paths->templates.$_file));
        $_path  = wire('config')->paths->templates.$_file;
```

**Comment by flipzoom** [comment]
This behavior is desired in order to prevent directory traversal. However, it is revised in an upcoming version.

**Comment by gusdecool** [comment]
yes, but if i try to get file upper directory from template. i will get error.

e.g: '../../bower/jquery/dist/jquery.min.js'

**Comment by flipzoom** [comment]
That's exactly what Directory Traversal mean. http://en.wikipedia.org/wiki/Directory_traversal
I know this is a problem with files outside of the ProcessWire-Template folder and i will remove this feature.

**Comment by gusdecool** [comment]
oh i see, so that's what you mean by Dir Traversal (I'm not familiar with the jargon).

But can you please explain why do you want to prevent dir traversal?
If it because of security, i think it is already outside scope of this module.

**Comment by gusdecool** [comment]
By The way, I'm asking the reason for my personal knowledge. not to offend
you :)
I love this module actually.

On Thu, Mar 6, 2014 at 9:22 PM, David Karich notifications@github.comwrote:

> That's exactly what Directory Traversal mean.
> http://en.wikipedia.org/wiki/Directory_traversal
> I know this is a problem with files outside of the ProcessWire-Template
> folder and i will remove this feature.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/FlipZoomMedia/ProcessWire-AIOM-All-In-One-Minify/issues/12#issuecomment-36886858
> .

## 

_Budi Arsana_

Flexi: 62 361 8607816
Website: www.gusdecool.com
Email: gusdecool@gmail.com or gusdecool@me.com

**Comment by flipzoom** [comment]
Yes it has a security background, but that comes more from the fact that I usually supervising other projects that require a very high level of security. For this module, it is certainly a little over the top. :) Anyway, I have introduced an option in the backend and in the new version 3.1.2 to disable the filter.

Greetings from Germany, 
Dave
