### ISSUE TITLE
Windows 8 AIOM giving 404 error (stylesheets/JS)

### ISSUE THREAD

**Issue by gauravtiwari** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#13]
Hello,

On accessing site using AIOM on windows the assets are not loaded -  404 not found.

Please if you can point me in right direction. 

Thank you,
Gaurav

**Comment by flipzoom** [comment]
I'm not sure if I understand you correctly. You're talking about a server environment on Windows 8? Or is a website that uses AIOM not display properly on your Windows 8 PC? Do you have a concrete example, URL or other code snippets for me? Have you seen in the log file of ProcessWire? What version will you be using? PW, AIOM, PHP.

Best Regards, 
Dave

**Comment by klor** [comment]
This will happen when a stylesheet include resources such as fonts and images using relative urls.

Bootstrap does this, among many others. Out of the box, Bootstrap attempts to load fonts using url/src, as here: url('../fonts/glyphicons-halflings-regular.eot'). Example from [bootstrap.css](https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.css) (3.2.0):

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('../fonts/glyphicons-halflings-regular.eot');
  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

The relative urls work fine when the CSS files are stored in their default folders. But when the CSS files are moved by AIOM to the /site/assets/aiom/ folder, the relative urls stop working. Consequently the user gets a 404.

Workaround:
Change all urls to absolute paths manually.

Suggested solution:

Rewrite relative paths, as in this example that uses bootstrap.css:
1. bootstrap.css (original) is located in: /site/templates/css/bootstrap.css
2. "../fonts" is rewritten to "/site/templates/fonts"
3. The urls will now work again.

**Comment by klor** [comment]
(The suggested solution is an alternative to your "Allow Directory Traversal".)
