### ISSUE TITLE
Debug mode results in "Division by zero" error

### ISSUE THREAD

**Issue by piercers** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#15]
When turning debug mode on, the stylesheet does not get parsed correctly and gives this error in the page's head:

"Division by zero in .../site/modules/AllInOneMinify/lib/Less/Less.php on line 2896"

When debug mode is off in ProcessWire, things run just fine. Please let me know what other information I can provide.

**Comment by flipzoom** [comment]
Can you send me your LESS file so I can reproduce the error somehow? Please send it to support@flipzoom.de. 

Dave
