### ISSUE TITLE
Compiled files are empty

### ISSUE THREAD

**Issue by tyssen** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#16]
AOIM is generating CSS and js files but they're coming up blank (except for a comment if I turn on dev mode).

The site is running PW 2.4 and I'm using AOIM 3.1.3.

Files are in a folder outside my templates directory but I've turned on directory traversal. 

I've also got HTML minify turned on but it's not minifying.

**Comment by tyssen** [comment]
Any idea about what's going on with this? Still getting blank compiled files although HTML minification is working as expected.

**Comment by somatonic** [comment]
Directory traversal seem to only works only with relative paths "../../" etc. 

Also there seems to be an issue with turning this option on/off. Not sure.

**Comment by tyssen** [comment]
Yes, relative paths has solved the issue for me.
