### ISSUE TITLE
Rewriting error when PWdocRoot != ServerDocRoot

### ISSUE THREAD

**Issue by kulmjens** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#18]
Hi there,
as my Processwire installation is in a subdirectory and under a subdomain, I came across a problem where all URIs in the minified CSS file were wrong. The problem is that my `$_SERVER['DOCUMENT_ROOT']` differs from the document root of my processwire.

``` php
docRoot of PW: /home/htdocs/processwire
$_SERVER['DOCUMENT_ROOT']: /home/htdocs
```

URIs in CSS as they are `/processwire/site/templates/styles/images/image.jpg` 
URIs in CSS as they should be `/site/templates/styles/images/image.jpg`

The Rewrite-Function in `site/modules/AllInOneMinify/lib/UriRewriter.php` uses the docRoot as third parameter. But in line 573 of `AllInOneMinify.module` there is no third parameter given, resulting in the Rewrite-Function to use `$_SERVER['DOCUMENT_ROOT']` as value.

So after changing line 573 of `AllInOneMinify.module` from

``` php
$_css_src = (!empty($_css_src)) ? Minify_CSS_UriRewriter::rewrite($_css_src, dirname($stylesheet['absolute_path'])) : $_css_src;
```

to

``` php
$_css_src = (!empty($_css_src)) ? Minify_CSS_UriRewriter::rewrite($_css_src, dirname($stylesheet['absolute_path']),wire('config')->paths->root) : $_css_src;
```

everything worked as expected. :-)

**Comment by marvinscharle** [comment]
Hi kulmjens,

I included your bug fix in the latest commit in the [Beta-Repository](https://github.com/conclurer/ProcessWire-AIOM-All-In-One-Minify/tree/AIOM-Beta]).

Thank you for you patience.

Marvin
