### ISSUE TITLE
Directory Traversal option wrong logic?

### ISSUE THREAD

**Issue by somatonic** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#21]
```
$_path  = (self::$directoryTraversal !== true) ? str_ireplace(array('../', './', '%2e%2e%2f', '..%2F'), '', wire('config')->paths->templates.$_file) : wire('config')->paths->templates.$_file;
```

This is true when the option is disabled,

```
self::$directoryTraversal   = ($this->directory_traversal == 1) ? true : false;
```

If option to traverse files is enabled (checkbox)  the "self::$directoryTraversal" will be "true"

Do I miss something?

**Comment by somatonic** [comment]
Hmm seems to work correctly, but don't get it. If all is ok ignore this.

**Comment by marvinscharle** [comment]
Hi soma,

I also do think, that this looks correctly. If something is not working properly, please open a new ticket. 

Thank you!
