### ISSUE TITLE
css minify script issue with removing empty {}

### ISSUE THREAD

**Issue by somatonic** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#23]
In the CSSMin php
// ------------------------------------------------------------------------
// Remove empty blocks.
// ------------------------------------------------------------------------
// $_source = preg_replace('/}[^\/}]+{}/', '}', $_source);

I had to comment out because I like to have some media query in some css empty while developing. The removing of the empty brackets lead to unexpected results with "open" media queries.

**Comment by marvinscharle** [comment]
Hi soma, 

in my opinion, empty brackets should be removed. How did the empty brackets influence your code?

If they were removed incompletely, this could be a serious bug. Did this happen again? 

Thank you in advance!

**Comment by somatonic** [comment]
I reviewed this and can't remember what exactly the case was...

But I managed to get a faulty replacement like the "}" but only if there's a rule before it and in the media query a empty rule

```
.text{
    color: #fff;
}

@media only screen and (min-width: 200px) {
    .text {
    }
}
```

This gives me

```
.text{color: #fff}}
```

This

```
.text{
}
@media only screen and (min-width: 200px) {
    .text{
    }
    .text2{
    }
}
```

gives me

```
.text{}.text2{}}
```

So it would be nice to have a fix for this cases

**Comment by marvinscharle** [comment]
This is related to our intension to switch to a third-party CSS compressor (#34). I think, the problem will be solved automatically.

**Comment by hwmaier** [comment]
I just tested the two cases which somatonic reported and the new YUI CSS compressor handles those correctly. The first case results in 

```
.text{color:#fff}
```

The second case results in no output as the resulting style is empty.

**Comment by marvinscharle** [comment]
Soma, can you please verify if the current version of AIOM (3.2) fixes this issue?

**Comment by marvinscharle** [comment]
Sorry - I read over the answer of @hwmaier. In this case, I think this issue is solved. @somatonic: If the problem still occurs, feel free to reopen this issue.
