### ISSUE TITLE
Problems with line endings: Less files checkout from GitHub are processed differently from those I upload by FTP

### ISSUE THREAD

**Issue by cpl-repo** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#25]
If I use on my server the same less files with AIOM+:
- checked out from GitHub
- uploaded by FTP

the final CSS are less-compiled differently.

When I add the less files to GitHub I get warning that my line-endings have been converted.

This might be due to different line endings on Windows and Linux.
Can you reproduce that error?

**Comment by cpl-repo** [comment]
The error occured when I put a couple of linebreaks (e.g. 5) in a row.
If I remove them, both versions (github + ftp) are compiled correctly.

**Comment by marvinscharle** [comment]
Hi cpl-repo,

in which environment are you working? Windows has different line-endings than Unix-based systems. GitHub - as far as I now - uses Unix line endings.

Furthermore, a warning when committing to GitHub seems to be a less-concerning problem for ProcessWire systems - as long as the files work properly on browsers.

Does this problem have any other negative effects beside the warning?

**Comment by marvinscharle** [comment]
This does not seem to be a problem anymore. Please reopen if the problem occurs in the future.
