### ISSUE TITLE
Feature request: Preserve special comments like /*! ... */

### ISSUE THREAD

**Issue by hwmaier** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#34]
Some comments must not be removed from CSS for copyright/license reasons. Most other compression tools leave such comments intact once they are tagged with an explanation mark.

```
/*!  This comment is not removed */
```

I would suggest to add this feature to AIOM, I could provide a patch to the comment regex.

**Comment by hwmaier** [comment]
Example how YUI Compresser is doing this:

http://yui.github.io/yuicompressor/css.html

**Comment by marvinscharle** [comment]
Thanks for the report. It would be great if you could supply such a regex. 

As a midterm goal, we're planning to switch to a third-party CSS compressor - this will solve the other problems regarding CSS compression (like your other topic #33).

**Comment by hwmaier** [comment]
In fact I had the same thought, why not switching to a more widely used compressor library rather fixing edge cases on the current one. As the usage base for PW is always smaller compared to other libraries it will be difficult to maintain an keep up.

For the CSS part, why not switch to the YUI CSS compressor which is also used by the Minfiy lib from Steve Clay (http://code.google.com/p/minify) which I used for years.

https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port 

that would solve the comment issue and the other issue with the :hover attribute I reported earlier.

**Comment by hwmaier** [comment]
I happy to take the lead on this and prepare a pull request with the YUI CSS lib.

**Comment by marvinscharle** [comment]
Thank you for your willingness to contribute to this repository. I'm looking forward to include your enhancement.

**Comment by hwmaier** [comment]
Done. The changes to the code are quite minimal. I bumped the version number to 3.2.0 as this is not a minor change. I tested it briefly on my site and it now handles the :hover case correctly and preserves /!\* comments as well.
Changes are in my fork: https://github.com/hwmaier/ProcessWire-AIOM-All-In-One-Minify

My fork also contains another change which adds support for direct passing of ProcessWire's $config->script and $config->styles variables. With that you can do this:

```
<link rel="stylesheet" href="<?=AllInOneMinify::CSS($config->styles)?>">
```

and

```
<script type="text/javascript" src="<?=AllInOneMinify::JS($config->scripts)?>"></script>
```

Its up to you as maintainer to decide this also to be a useful feature and include it in the head revision.

**Comment by marvinscharle** [comment]
Thank you for you effort! Can you create a pull request for those changes?

**Comment by hwmaier** [comment]
There is one already pending which now includes the latest cssmin changes. Have not updated the readme file though.

https://github.com/conclurer/ProcessWire-AIOM-All-In-One-Minify/pull/31

**Comment by hwmaier** [comment]
Feature is now supported in v 3.2.
