### ISSUE TITLE
Permission 0777 not safe in some environments

### ISSUE THREAD

**Issue by ryancramerdesign** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#44]
Thanks for this module. I was just implementing here for a client, and noticed it using hard-coded 0777 permission rather than ProcessWire's `$config->chmodDir` and `$config->chmodFile`. The server I'm working with is a typical shared server, where 0777 for dirs (0666 for files) is not safe because it means other users on the server and modify the files. The same is true in many hosting environments. I was wondering if you would consider using the PW config properties I mentioned above instead, or just use PW's `wireChmod('/path/to/dir/or/file');` which automatically makes them writable consistent with the PW configured settings. Assuming those PW settings are configured properly, this ensures the safety of any writable directories or files.

**Comment by adrianbj** [comment]
Hey guys - what is happening with this - it looks like a critical, but easy thing to fix!

**Comment by 14pixels** [comment]
Any Updates on this issue? Or is this module not maintained anymore?

**Comment by flipzoom** [comment]
We are sorry that it took a little longer. I currently have a lot to do. The problem has been solved.
