### ISSUE TITLE
Print css content as inline

### ISSUE THREAD

**Issue by ghost** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#55]
With the introduction of [AMP](https://www.ampproject.org) technology by google, i would know if is possible to print the generated css as inline element instead of using link tag, because in AMP spec this tag aren't allowed for css but only for fonts.

Best regards

**Comment by flipzoom** [comment]
Hi Patrick,

currently AIOM+ has no method to output the content directly, but I have a not so nice Workarround for you. I put this feature on the "AIOM4" roadmap.

``` php
echo file_get_contents( $config->paths->assets . str_replace($config->urls->assets, '', AIOM::CSS('styles/main.css')) );
```

Best regards, 
David

**Comment by ghost** [comment]
Thank's a lot for your reply David, and for the code.
Best regards
