### ISSUE TITLE
HTML Minify makes text-align:justify CSS grid unusable

### ISSUE THREAD

**Issue by philippreiner** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#6]
(Just a small, not so important issue:)

Using the text-align:justify CSS grid doesn't work in combination with the minified HTML. The grid will shift a little bit left. Maybe some invisible characters are removed?

I can solve the problem by deactivating the HTML minify output.

More info:
http://justifygrid.com/

**Comment by flipzoom** [comment]
Hi Philipp, 

this is not a bug of AIOM. AIOM removes all whitespaces between two tags. The justifygrid-framework but requires one or more whitespaces between the grid elements. If you want to use HTML Minify, you need to put between the grid elements a forced whitespace using html entities `&nbsp;`. Then it works.

Here is an example with the demo of justifygrid: 

**Original (produced your reported problem)**

``` html
<div class="page">
  <header>
    <h1><a href="http://justifygrid.com">Justify Grid</a></h1>
  </header>
  <nav>
    <p>Justify Grid is a new way to create layouts.
       Click on logo for more info.</p>
  </nav>
  <div class="main">
    <h1>Image Gallery</h1>
    <div class="image"></div>
    <div class="image"></div>
    <div class="image"></div>
  </div>
  <footer>
    <p>Justify Grid is produced by <a href="http://crocodillon.com">CrocoDillon</a></p>
  </footer>
</div>
```

**So you have to change it if you want to use HTML minimization:**

``` html
<div class="page">
  <header>
    <h1><a href="http://justifygrid.com">Justify Grid</a></h1>
  </header>
  <nav>
    <p>Justify Grid is a new way to create layouts.
       Click on logo for more info.</p>
  </nav>&nbsp;
  <div class="main">
    <h1>Image Gallery</h1>
    <div class="image"></div>&nbsp;
    <div class="image"></div>&nbsp;
    <div class="image"></div>
  </div>
  <footer>
    <p>Justify Grid is produced by <a href="http://crocodillon.com">CrocoDillon</a></p>
  </footer>
</div>
```

**Comment by isellsoap** [comment]
Why not include an option in the settings to have a space between two tags? Inserting extra meaningless markup to avoid this problem seems a bit weird to me.
