### ISSUE TITLE
Error when debug mode enable in config.php

### ISSUE THREAD

**Issue by ghost** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#8]
I have this error when debug mode is true and the module not work...

<br /><b>Strict Standards</b>:  Non-static method AllInOneMinify::JS() should not be called statically, assuming $this from incompatible context in <b>/home/myserver/public_html/mysite/site/templates/main.php</b> on line <b>138</b><br /><br /><b>Strict Standards</b>:  Non-static method AllInOneMinify::_fileArray() should not be called statically, assuming $this from incompatible context in <b>/home/myserver/public_html/myserver/public_html/mysite/site/modules/AllInOneMinify/AllInOneMinify.module</b> on line <b>231</b><br /><br /><b>Strict Standards</b>:  Non-static method AllInOneMinify::_getCacheName() should not be called statically, assuming $this from incompatible context in <b>/home/myserver/public_html/demos/hotelkahve/site/modules/AllInOneMinify/AllInOneMinify.module</b> on line <b>232</b><br /><br /><b>Notice</b>:  Undefined variable: _timestamp in <b>/home/myserver/public_html/demos/hotelkahve/site/modules/AllInOneMinify/AllInOneMinify.module</b> on line <b>448</b><br />
/mysite/site/assets/aiom/js_27a4aa3dfbfbe40ad50d2f177f91e918.js">

**Comment by flipzoom** [comment]
Thank you JoZ3, 

The issue should now be resolved. It would be nice if you test it and give me know if it works. Thank you! The Fix is ​​in the current dev branch: https://github.com/FlipZoomMedia/ProcessWire-AIOM-All-In-One-Minify/tree/dev
